---
title: "Comparing supervised speech learning directly to human performance in speech perception"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE}
library(magrittr)
library("doParallel")
correct_ipa <- function(data){
  data <- data %>%
  dplyr::mutate(vowel_eng = 
                  ifelse(vowel_eng == "AE", "æ",
                  ifelse(vowel_eng == "UH", "ʊ",
                  ifelse(vowel_eng == "AH", "ʌ", 
                  ifelse(vowel_eng == "IH", "ɪ", vowel_eng)))),
                vowel_fr =
                  ifelse(vowel_fr == "A", "a",
                  ifelse(vowel_fr == "E", "ɛ", 
                  ifelse(vowel_fr == "OE", "œ",
                  ifelse(vowel_fr == "O", "ɔ",
                  ifelse(vowel_fr == "Y", "y",
                  ifelse(vowel_fr == "U", "u",
                  ifelse(vowel_fr == "I", "i", vowel_fr)))))))
                  )
  return(data)
}
correct_ipa_context <- function(data){
  data <- data %>%
  dplyr::mutate(context = 
                  ifelse(context == "V_Z", "v_z",
                  ifelse(context == "V_K", "v_k",
                  ifelse(context == "SH_S", "ʃ_s", 
                  ifelse(context == "Z_G", "z_g", 
                  ifelse(context == "V_P", "v_p", 
                  ifelse(context == "Z_D", "z_d",
                  ifelse(context == "Z_B", "z_b",
                  ifelse(context == "SH_B", "ʃ_b", 
                  ifelse(context == "V_SH", "v_ʃ",
                  ifelse(context == "Z_SH", "z_ʃ",
                  ifelse(context == "SH_V", "ʃ_v",       
                  ifelse(context == "V_F", "v_f", tolower(context))))))))))))))
  return(data)
}
emd_theme <- function(text_size=18) {
  return(ggplot2::theme_bw() +
           ggplot2::theme(text=ggplot2::element_text(size=text_size),
                          legend.position="bottom"))
}


cbPalette <- c("#E69F00", "#009E73", "#CC79A7")

```

```{r load-data, include=FALSE}
distances_bottle <- readr::read_csv("../model/unsupervised/bottleneck/distances_bottleneck.csv") 
distances_mfcc <- readr::read_csv("../model/mfccs/ark/distances_mfccs.csv")
distances_kmean <- readr::read_csv("../model/unsupervised/pqKmeans/1M_PQkmean_clustering/distances_kmeans.csv") 
humans <- readr::read_csv("./outputs/analysed_data_FINALstim.csv",
                          col_types=readr::cols(survey_time=readr::col_character())) %>%
  dplyr::select(-dplyr::contains("dist"), -X1) %>%
  dplyr::mutate(subject_language=ifelse(subject_language == "fr2", "fr",
                                        subject_language))

results <- humans %>%
  dplyr::left_join(distances_mfcc) %>%
  dplyr::mutate(delta_eng_kaldi=post_en_oth_x-post_en_tgt_x,
                delta_fr_kaldi=post_fr_oth_x-post_fr_tgt_x,
                delta_mfcc=mfcc_oth_x-mfcc_tgt_x,
                delta_eng_kaldi_s=scale(delta_eng_kaldi, center=FALSE)[,1],
                delta_fr_kaldi_s=scale(delta_fr_kaldi, center=FALSE)[,1],
                delta_mfcc_s=scale(delta_mfcc, center=FALSE)[,1],
                corr_ans_c=ifelse(corr_ans=="A", -1, 1),
                subject_language_c=ifelse(subject_language=="eng", -1, 1)) %>%
  dplyr::left_join(distances_bottle) %>%
  dplyr::mutate(delta_bottle=bottle_oth_x-bottle_tgt_x,
                delta_bottle_s=scale(delta_bottle, center=FALSE)[,1]) %>%
  dplyr::left_join(distances_kmean) %>%
  dplyr::mutate(delta_kmean2en=en_2_kmean_oth_x-en_2_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean2fr=fr_2_kmean_oth_x-fr_2_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean5en=en_5_kmean_oth_x-en_5_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean5fr=fr_5_kmean_oth_x-fr_5_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean10en=en_10_kmean_oth_x-en_10_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean10fr=fr_10_kmean_oth_x-fr_10_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean100en=en_100_kmean_oth_x-en_100_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean100fr=fr_100_kmean_oth_x-fr_100_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean500en=en_500_kmean_oth_x-en_500_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean500fr=fr_500_kmean_oth_x-fr_500_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean1000en=en_1000_kmean_oth_x-en_1000_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean1000fr=fr_1000_kmean_oth_x-fr_1000_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean42en=en_42_kmean_oth_x-en_42_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean61fr=fr_61_kmean_oth_x-fr_61_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean611en=en_611_kmean_oth_x-en_611_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean1565fr=fr_1565_kmean_oth_x-fr_1565_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean6000en=en_6000_kmean_oth_x-en_6000_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean6000fr=fr_6000_kmean_oth_x-fr_6000_kmean_tgt_x) %>%
  dplyr::mutate(delta_kmean2en_s=scale(delta_kmean2en,center=FALSE)[,1],
                delta_kmean2fr_s=scale(delta_kmean2fr,center=FALSE)[,1],
                delta_kmean5en_s=scale(delta_kmean5en,center=FALSE)[,1],
                delta_kmean5fr_s=scale(delta_kmean5fr,center=FALSE)[,1],
                delta_kmean10en_s=scale(delta_kmean10en,center=FALSE)[,1],
                delta_kmean10fr_s=scale(delta_kmean10fr,center=FALSE)[,1],
                delta_kmean100en_s=scale(delta_kmean100en,center=FALSE)[,1],
                delta_kmean100fr_s=scale(delta_kmean100fr,center=FALSE)[,1],
                delta_kmean500en_s=scale(delta_kmean500en,center=FALSE)[,1],
                delta_kmean500fr_s=scale(delta_kmean500fr,center=FALSE)[,1],
                delta_kmean1000en_s=scale(delta_kmean1000en,center=FALSE)[,1],
                delta_kmean1000fr_s=scale(delta_kmean1000fr,center=FALSE)[,1],
                delta_kmean42en_s=scale(delta_kmean42en,center=FALSE)[,1],
                delta_kmean61fr_s=scale(delta_kmean61fr,center=FALSE)[,1],
                delta_kmean611en_s=scale(delta_kmean611en,center=FALSE)[,1],
                delta_kmean1565fr_s=scale(delta_kmean1565fr,center=FALSE)[,1],
                delta_kmean6000en_s=scale(delta_kmean6000en,center=FALSE)[,1],
                delta_kmean6000fr_s=scale(delta_kmean6000fr,center=FALSE)[,1]) %>%
  correct_ipa %>% correct_ipa_context
```

```{r n}
humans %>%
  dplyr::select(subject_id, subject_language) %>%
  dplyr::distinct() %>%
  dplyr::group_by(subject_language) %>%
  dplyr::summarize(dplyr::n()) %>%
  dplyr::ungroup()
```

```{r global-abx-scores}
summary_overall <- results %>%
  dplyr::group_by(tripletid, context, vowel_fr, vowel_eng) %>%
  dplyr::summarize(ABX_eng_kaldi=delta_eng_kaldi[1]>0,
                   ABX_fr_kaldi=delta_fr_kaldi[1]>0,
                   ABX_bottle=delta_bottle[1]>0,
                   ABX_mfcc=delta_mfcc[1]>0,
                    ABX_kmean_2en=delta_kmean2en[1]>0,
                    ABX_kmean_2fr=delta_kmean2fr[1]>0,
                    ABX_kmean_5en=delta_kmean5en[1]>0,
                    ABX_kmean_5fr=delta_kmean5fr[1]>0,
                    ABX_kmean_10en=delta_kmean10en[1]>0,
                    ABX_kmean_10fr=delta_kmean10fr[1]>0,
                    ABX_kmean_100en=delta_kmean100en[1]>0,
                    ABX_kmean_100fr=delta_kmean100fr[1]>0,
                    ABX_kmean_500en=delta_kmean500en[1]>0,
                    ABX_kmean_500fr=delta_kmean500fr[1]>0,
                    ABX_kmean_1000en=delta_kmean1000en[1]>0,
                    ABX_kmean_1000fr=delta_kmean1000fr[1]>0,
                    ABX_kmean_42en=delta_kmean42en[1]>0,
                    ABX_kmean_61fr=delta_kmean61fr[1]>0,
                    ABX_kmean_611en=delta_kmean611en[1]>0,
                    ABX_kmean_1565fr=delta_kmean1565fr[1]>0,
                    ABX_kmean_6000en=delta_kmean6000en[1]>0,
                    ABX_kmean_6000fr=delta_kmean6000fr[1]>0,
                   ABX_human=mean(user_corr)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(context, vowel_fr, vowel_eng) %>%
  dplyr::summarize_at(dplyr::vars(dplyr::starts_with("ABX_")), mean) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize_at(dplyr::vars(dplyr::starts_with("ABX_")), mean) %>%
  dplyr::ungroup() %>%
  dplyr::summarize_at(dplyr::vars(dplyr::starts_with("ABX_")), mean)
summary_overall

write.csv(summary_overall, file = "summary_abx_score_eucl.csv")
```

```{r abx-by-language}
results %>%
  dplyr::group_by(subject_language, tripletid, context, vowel_fr, vowel_eng) %>%
  dplyr::summarize(ABX_human=mean(user_corr)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(subject_language, context, vowel_fr, vowel_eng) %>%
  dplyr::summarize_at(dplyr::vars(dplyr::starts_with("ABX_")), mean) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(subject_language, vowel_fr, vowel_eng) %>%
  dplyr::summarize_at(dplyr::vars(dplyr::starts_with("ABX_")), mean) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(subject_language) %>%
  dplyr::summarize_at(dplyr::vars(dplyr::starts_with("ABX_")), mean) %>%
  dplyr::ungroup()
```


```{r summary-human}
model_nuisance <- lme4::glmer(
  user_corr ~ corr_ans_c*subject_language_c + (1|subject_id),
  family=binomial(link="probit"),
  data=results
)
summary_fr <- results %>%
  dplyr::filter(subject_language=="fr") %>%
  dplyr::mutate(pred_nuisance_fr=
                  predict(model_nuisance, .)) %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::mutate(p_nuis=pnorm(pred_nuisance_fr)) %>%
  dplyr::summarize(resid_fr=mean(user_corr-p_nuis),
                   pct_fr=mean(user_corr)) %>%
  dplyr::ungroup()
summary_eng <- results %>%
  dplyr::filter(subject_language=="eng") %>%
  dplyr::mutate(pred_nuisance_eng=
                  predict(model_nuisance, .)) %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::mutate(p_nuis=pnorm(pred_nuisance_eng)) %>%
  dplyr::summarize(resid_eng=mean(user_corr-p_nuis),
                   pct_eng=mean(user_corr)) %>%
  dplyr::ungroup()
summary_h <- dplyr::left_join(summary_fr, summary_eng)
summary_h_bypair <- summary_h %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, vowel_fr, vowel_eng) %>%
  dplyr::summarize(resid_fr=mean(resid_fr),
                   resid_eng=mean(resid_eng),
                   pct_fr=mean(pct_fr),
                   pct_eng=mean(pct_eng)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(resid_fr=mean(resid_fr),
                   resid_eng=mean(resid_eng),
                   pct_fr=mean(pct_fr),
                   pct_eng=mean(pct_eng)) %>%
  dplyr::ungroup() 
summary_h_bylang <- tidyr::gather(summary_h_bypair, key=`Native language`,
                                      value=Accuracy, pct_fr, pct_eng) %>%
  dplyr::mutate(`Native language`=ifelse(`Native language`=="pct_fr",
                                         "French listeners",
                                         "English listeners"),
                `English vowel`=vowel_eng, `French vowel`=vowel_fr)

summary_m <- results %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pct_fr=delta_fr_kaldi[1]>0,
                   pct_eng=delta_eng_kaldi[1]>0) %>%
  dplyr::ungroup()
summary_m_bypair <- summary_m %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, vowel_fr, vowel_eng) %>%
  dplyr::summarize(pct_fr=mean(pct_fr),
                   pct_eng=mean(pct_eng)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(pct_fr=mean(pct_fr),
                   pct_eng=mean(pct_eng)) %>%
  dplyr::ungroup() 
summary_m_bylang <- tidyr::gather(summary_m_bypair, key=`Native language`,
                                      value=Accuracy, pct_fr, pct_eng) %>%
  dplyr::mutate(`Native language`=ifelse(`Native language`=="pct_fr",
                                         "French model",
                                         "English model"),
                `English vowel`=vowel_eng, `French vowel`=vowel_fr)
```

```{r accuracy-plot}
ggplot2::ggplot(summary_h_bylang,
                ggplot2::aes(x=`French vowel`, y=`English vowel`,
                fill=Accuracy)) +
  ggplot2::geom_tile(colour="black") +
  ggplot2::scale_fill_gradient2(low = "black",
                                mid = "deepskyblue4",
                                high = "bisque",
                                midpoint=0.45,
                               limits = c(0, 1.00),
                               breaks=seq(0, 1.00, .1),
                               labels=as.character(seq(0, 1.00, .1)*100)) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=18, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::guides(fill=ggplot2::guide_colourbar(title.position="bottom",
                                                title.hjust=0.5)) +
  ggplot2::labs(x="French vowel", y="English vowel", fill="Percent accuracy") +
  ggplot2::facet_grid(`Native language` ~ .) +
  ggplot2::ggsave("figures/Figure_AccuraciesGrouped.png", width=4, height=5)
```



```{r}
ggplot2::ggplot(summary_m_bylang,
                ggplot2::aes(x=`French vowel`, y=`English vowel`,
                fill=Accuracy)) +
  ggplot2::geom_tile(colour="black") +
  ggplot2::scale_fill_gradient2(low = "black",
                                mid = "deepskyblue4",
                                high = "bisque",
                                midpoint=0.45,
                               limits = c(0, 1.00),
                               breaks=seq(0, 1.00, .1),
                               labels=as.character(seq(0, 1.00, .1)*100)) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=18, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::guides(fill=ggplot2::guide_colourbar(title.position="bottom",
                                                title.hjust=0.5)) +
  ggplot2::labs(x="French vowel", y="English vowel", fill="Percent accuracy") +
  ggplot2::facet_grid(`Native language` ~ .) +
  ggplot2::ggsave("figures/Figure_AccuraciesModels.png", width=4, height=5)
```







```{r cor-human-eng-fr}
with(summary_h, cor(resid_fr, resid_eng))
with(summary_h_bypair, cor(resid_fr, resid_eng))
```

```{r plot-eng-fr-byvowel}
ggplot2::ggplot(summary_h_bypair,
                ggplot2::aes(y=resid_fr, x=resid_eng,
                             label=paste0(vowel_eng, ":", vowel_fr))) +
  ggplot2::geom_abline(slope=1, intercept=0, lty="dashed",
                       lwd=0.6, colour="#aaaaaa") +
  ggplot2::geom_point() +
  ggrepel::geom_text_repel(family="Times New Roman", size=4.9) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=18, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::labs(x="Corrected accuracy (English)",
                 y="Corrected accuracy (French)") +
  ggplot2::ggsave("figures/Figure_FrVsEg.png", width=7, height=4)
```



```{r lm-predict-responses-from-deltas}
model_global_bottle <- lme4::glmer(
              user_corr ~ delta_bottle_s + subject_language_c*corr_ans_c +
              (1|subject_id) + (1|tripletid), 
              family=binomial(link="probit"), data=results)
model_global_mfcc <- lme4::glmer(
              user_corr ~ delta_mfcc_s + subject_language_c*corr_ans_c +
              (1|subject_id) + (1|tripletid), 
              family=binomial(link="probit"), data=results)
model_global_engdp <- lme4::glmer(
              user_corr ~ delta_eng_kaldi_s + subject_language_c*corr_ans_c +
              (1|subject_id) + (1|tripletid), 
            family=binomial(link="probit"), data=results)
model_global_frdp <- lme4::glmer(
              user_corr ~ delta_fr_kaldi_s +  subject_language_c*corr_ans_c + 
              (1|subject_id) + (1|tripletid), 
            family=binomial(link="probit"), data=results)
```


```{r compare-lm-deltas}
lme4::fixef(model_global_bottle)
lme4::fixef(model_global_mfcc)
lme4::fixef(model_global_engdp)
lme4::fixef(model_global_frdp)
AIC(model_global_bottle)
AIC(model_global_mfcc)
AIC(model_global_engdp)
AIC(model_global_frdp)
```


```{r lm-native-language-effect}
results <- results %>%
  dplyr::mutate(native_machine=ifelse(subject_language == "eng",
                                      delta_eng_kaldi_s, delta_fr_kaldi_s),
                nonnative_machine=ifelse(subject_language == "eng",
                                         delta_fr_kaldi_s, delta_eng_kaldi_s))
model_native <- lme4::glmer(
              user_corr ~ native_machine + subject_language_c*corr_ans_c +
              (1|subject_id) + (1|tripletid), 
            family=binomial(link="probit"), data=results)
model_nonnative <- lme4::glmer(
              user_corr ~ nonnative_machine +  subject_language_c*corr_ans_c + 
              (1|subject_id) + (1|tripletid), 
            family=binomial(link="probit"), data=results)
```


```{r model-comparison-native-language-effect}
lme4::fixef(model_native)
lme4::fixef(model_nonnative)
AIC(model_native)
AIC(model_nonnative)

AIC(model_nonnative)-AIC(model_native)
```

```{r}
dplyr::tibble(AIC_nonnative = AIC(model_nonnative),
                          AIC_native =  AIC(model_native))
```


```{r lm-native-language-effect-kmeans}
get_table_native <- function(DATA,
                    DELTA_MODEL_EN_S,
                    DELTA_MODEL_FR_S){
  DELTA_MODEL_EN_S <- enquo(DELTA_MODEL_EN_S)
  DELTA_MODEL_FR_S <- enquo(DELTA_MODEL_FR_S)
                    
  DATA <- DATA %>%
  dplyr::mutate(native_machine=ifelse(subject_language == "eng",
                                      !! DELTA_MODEL_EN_S, !! DELTA_MODEL_FR_S),
                nonnative_machine=ifelse(subject_language == "eng",
                                      !! DELTA_MODEL_FR_S, !! DELTA_MODEL_EN_S))
  return(DATA)
}

get_native_effect <- function(DATA,
                              DELTA_MODEL_EN_S,
                              DELTA_MODEL_FR_S,
                              NAME){
  DELTA_MODEL_EN_S <- enquo(DELTA_MODEL_EN_S)
  DELTA_MODEL_FR_S <- enquo(DELTA_MODEL_FR_S)
  DF <- get_table_native(DATA,
                         !! DELTA_MODEL_EN_S,
                         !! DELTA_MODEL_FR_S)
  model_native <- lme4::glmer(
                user_corr ~ native_machine + subject_language_c*corr_ans_c +
                (1|subject_id) + (1|tripletid), 
              family=binomial(link="probit"), data=DF)
  model_nonnative <- lme4::glmer(
                user_corr ~ nonnative_machine +  subject_language_c*corr_ans_c + 
                (1|subject_id) + (1|tripletid), 
              family=binomial(link="probit"), data=DF)
  lme4::fixef(model_native)
  lme4::fixef(model_nonnative)
  RESULT <- dplyr::tibble(AIC_nonnative = AIC(model_nonnative),
                          AIC_native =  AIC(model_native),
                          AIC_diff = AIC(model_nonnative) -  AIC(model_native),
                          K_number = NAME)
  return(RESULT)
}
```




```{r random-baseline-model-comparison-native-language}
# STAT_CACHE_FILE <- "statistics_native_nonnative.RData"
# if (!file.exists(STAT_CACHE_FILE)) {
#   N_SAMPLES <- 9999
#   N_CORES <- 20
#   doParallel::registerDoParallel(cores=N_CORES)
#   `%dopar%` <- foreach::`%dopar%`
#   statistics_l <- foreach::foreach(i=1:N_SAMPLES) %dopar% {
#     results_fake <- results %>%
#       dplyr::mutate(fake_subject_language=sample(subject_language),
#                     native_machine=ifelse(fake_subject_language == "eng",
#                                       delta_eng_kaldi_s, delta_fr_kaldi_s),
#                     nonnative_machine=ifelse(fake_subject_language == "eng",
#                                          delta_fr_kaldi_s, delta_eng_kaldi_s))
#     model_native_i <- lme4::glmer(
#       user_corr ~ native_machine + subject_language_c*corr_ans_c +
#         (1|subject_id) + (1|tripletid), 
#       family=binomial(link="probit"), data=results_fake)
#     model_nonnative_i <- lme4::glmer(
#       user_corr ~ nonnative_machine +  subject_language_c*corr_ans_c + 
#         (1|subject_id) + (1|tripletid), 
#       family=binomial(link="probit"), data=results_fake)
#     AIC(model_native_i)-AIC(model_nonnative_i)
#   }
#   statistics <- unlist(statistics_l)
#   save(statistics, file=STAT_CACHE_FILE)
# } else {
#   load(STAT_CACHE_FILE)
# }
# pval_auc <- sum(statistics <=
#            (AIC(model_native)-AIC(model_nonnative)))/(length(statistics)+1)
# print(pval_auc)
```



```{r summarize-delta}
delta_fr <- results %>%
  dplyr::filter(subject_language=="fr") %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pred_fr=delta_fr_kaldi[1]) %>%
  dplyr::ungroup()
delta_eng <- results %>%
  dplyr::filter(subject_language=="eng") %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pred_eng=delta_eng_kaldi[1]) %>%
  dplyr::ungroup()
delta <- dplyr::left_join(delta_fr, delta_eng)
delta_bypair <- delta %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, vowel_fr, vowel_eng) %>%
  dplyr::summarize(pred_fr=mean(pred_fr),
                   pred_eng=mean(pred_eng)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(pred_fr=mean(pred_fr),
                   pred_eng=mean(pred_eng)) %>%
  dplyr::ungroup() 
```


```{r plot-eng-fr-model-byvowel}
ggplot2::ggplot(delta_bypair,
                ggplot2::aes(y=pred_fr, x=pred_eng,
                             label=paste0(vowel_eng, ":", vowel_fr))) +
  ggplot2::geom_point() +
  ggrepel::geom_text_repel(family="Times New Roman", size=4.9) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=18, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::labs(x="δ (English kaldi)",
                 y="δ (French kaldi)") +
  ggplot2::ggsave("figures/Figure_FrVsEg_model.png", width=7, height=4)
```


```{r corrected-delta-predictions}
model_native_for_pred <- lme4::glmer(
              user_corr ~ native_machine + subject_language_c*corr_ans_c +
              (1|subject_id), 
            family=binomial(link="probit"), data=results)
preds_fr <- results %>%
  dplyr::filter(subject_language=="fr") %>%
  dplyr::mutate(pred_uncorrected_fr=predict(model_native_for_pred, .),
                pred_nuisance_fr=predict(model_native_for_pred,
                                         newdata=dplyr::mutate(., native_machine=0))) %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::mutate(p_model=pnorm(pred_uncorrected_fr),
                p_nuis=pnorm(pred_nuisance_fr)) %>%
  dplyr::summarize(pred_fr=mean(p_model-p_nuis)) %>%
  dplyr::ungroup()
preds_eng <- results %>%
  dplyr::filter(subject_language=="eng") %>%
  dplyr::mutate(pred_uncorrected_eng=predict(model_native_for_pred, .),
                pred_nuisance_eng=predict(model_native_for_pred,
                                         newdata=dplyr::mutate(., native_machine=0))) %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::mutate(p_model=pnorm(pred_uncorrected_eng),
                p_nuis=pnorm(pred_nuisance_eng)) %>%
  dplyr::summarize(pred_eng=mean(p_model-p_nuis)) %>%
  dplyr::ungroup()
preds <- dplyr::left_join(preds_fr, preds_eng)
preds_bypair <- preds %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, vowel_fr, vowel_eng) %>%
  dplyr::summarize(pred_fr=mean(pred_fr),
                   pred_eng=mean(pred_eng)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(pred_fr=mean(pred_fr),
                   pred_eng=mean(pred_eng)) %>%
  dplyr::ungroup() 
differences_machine <- preds %>%
  dplyr::mutate(`Native language effect (models)`=(pred_fr-pred_eng))
differences_machine_grouped <- differences_machine %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, vowel_fr, vowel_eng) %>%
  dplyr::summarize(`Native language effect (models)`=
                     mean(`Native language effect (models)`)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(`Native language effect (models)`=
                     mean(`Native language effect (models)`)) %>%
  dplyr::ungroup() 
differences_machine_bycontext <- differences_machine %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, context) %>%
  dplyr::summarize(`Native language effect (models)`=
                     mean(`Native language effect (models)`)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(context) %>%
  dplyr::summarize(`Native language effect (models)`=
                     mean(`Native language effect (models)`)) %>%
  dplyr::ungroup()
differences_machine_byspeaker <- differences_machine %>%
  dplyr::group_by(vowel_fr, vowel_eng, speaker_OTH, speaker_TGT,
                  speaker_X) %>%
  dplyr::summarize(`Native language effect (models)`=
                     mean(`Native language effect (models)`)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(speaker_TGT, speaker_OTH, speaker_X) %>%
  dplyr::summarize(`Native language effect (models)`=
                     mean(`Native language effect (models)`)) %>%
  dplyr::ungroup()
differences_human <- summary_h %>%
  dplyr::mutate(`Native language effect (listeners)`=
                     (resid_fr-resid_eng)) 
differences_human_grouped <- differences_human %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, vowel_fr, vowel_eng) %>%
  dplyr::summarize(`Native language effect (listeners)`=
                     mean(`Native language effect (listeners)`)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(`Native language effect (listeners)`=
                     mean(`Native language effect (listeners)`)) %>%
  dplyr::ungroup() 
differences_human_bycontext <- differences_human %>%
  dplyr::group_by(speaker_OTH, speaker_TGT,
                  speaker_X, context) %>%
  dplyr::summarize(`Native language effect (listeners)`=
                     mean(`Native language effect (listeners)`)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(context) %>%
  dplyr::summarize(`Native language effect (listeners)`=
                     mean(`Native language effect (listeners)`)) %>%
  dplyr::ungroup()
differences_human_byspeaker <- differences_human %>%
  dplyr::group_by(vowel_fr, vowel_eng, speaker_OTH, speaker_TGT,
                  speaker_X) %>%
  dplyr::summarize(`Native language effect (listeners)`=
                     mean(`Native language effect (listeners)`)) %>%
  dplyr::ungroup() %>%
  dplyr::group_by(speaker_TGT, speaker_OTH, speaker_X) %>%
  dplyr::summarize(`Native language effect (listeners)`=
                     mean(`Native language effect (listeners)`)) %>%
  dplyr::ungroup()
nle <- dplyr::left_join(differences_human, differences_machine)
nle_grouped <- dplyr::left_join(differences_human_grouped,
                                differences_machine_grouped)
nle_bycontext <- dplyr::left_join(differences_human_bycontext,
                                differences_machine_bycontext)
nle_byspeaker <- dplyr::left_join(differences_human_byspeaker,
                                differences_machine_byspeaker)
```

```{r plot-nle-global}
ggplot2::ggplot(nle,
                ggplot2::aes(x=`Native language effect (models)`,
                             y=`Native language effect (listeners)`,
                             label=paste0(vowel_eng, ":", vowel_fr))) +
  ggplot2::geom_smooth(method="lm",  fullrange=TRUE, se=TRUE, lty="dashed",
                       lwd=0.6,  colour="#aaaaaa") +
  ggplot2::geom_point() +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=17.5, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::labs(x="Native language effect (kaldi)",
                 y="Native language effect (humans)") +
  ggplot2::scale_x_continuous(expand=c(0,0), limits=c(-0.065, 0.065)) +
  ggplot2::coord_cartesian(xlim=c(-0.065, 0.065), ylim=c(-0.45, 0.35)) +
  ggplot2::ggsave("figures/Figure_NLE_Item.png", width=7, height=4)
```

```{r plot-nle-byvowel}
ggplot2::ggplot(nle_grouped,
                ggplot2::aes(x=`Native language effect (models)`,
                             y=`Native language effect (listeners)`,
                             label=paste0(vowel_eng, ":", vowel_fr))) +
  ggplot2::geom_smooth(method="lm", fullrange=TRUE, se=TRUE, lty="dashed",
                       lwd=0.6, colour="#aaaaaa") +
  ggplot2::geom_point() +
  ggrepel::geom_text_repel(family="Times New Roman", size=4.9) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=17.5, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::scale_x_continuous(expand=c(0,0), limits=c(-0.035, 0.035)) +
  ggplot2::coord_cartesian(xlim=c(-0.035, 0.035), ylim=c(-0.25, 0.2346)) +
  ggplot2::labs(x="Native language effect (kaldi)",
                 y="Native language effect (humans)") +
  ggplot2::ggsave("figures/Figure_NLE_Vowel.png", width=7, height=4)
```

```{r plot-nle-bycontext}
ggplot2::ggplot(nle_bycontext,
                ggplot2::aes(x=`Native language effect (models)`,
                             y=`Native language effect (listeners)`,
                             label=context)) +
  ggplot2::geom_smooth(method="lm", fullrange=TRUE, se=TRUE, lty="dashed",
                       lwd=0.6, colour="#aaaaaa") +
  ggplot2::geom_point() +
  ggrepel::geom_text_repel(family="Times New Roman", size=4.9) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=17.5, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::scale_x_continuous(expand=c(0,0), limits=c(-0.05, 0.02)) +
  ggplot2::coord_cartesian(xlim=c(-0.05, 0.02), ylim=c(-0.25, 0.2346)) +
  ggplot2::labs(x="Native language effect (kaldi)",
                 y="Native language effect (humans)") +
  ggplot2::ggsave("figures/Figure_NLE_Context.png", width=7, height=4)
```




```{r bottle}
delta_bottle_accuracy <- results %>%
  dplyr::mutate(pred_bottle = ifelse(delta_bottle > 0, 1, 0)) 

delta_bottle_v_accuracy <- delta_bottle_accuracy %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pred_bottle=mean(pred_bottle)) %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(accuracy_bottle=mean(pred_bottle)) %>%
  dplyr::ungroup() 

overall_hums <- results %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pct_humans=mean(user_corr)) %>%
  dplyr::group_by(tripletid) %>%
  dplyr::summarize(accuracy_human=mean(pct_humans)) %>%
  dplyr::ungroup() 


overall_hums_v <- results %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pct_humans=mean(user_corr)) %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(accuracy_human=mean(pct_humans)) %>%
  dplyr::ungroup() 

bottle_humans_v_overall <- dplyr::left_join(delta_bottle_v_accuracy, overall_hums_v)

delta_bottle_c <- delta_bottle %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pred_bottle=mean(delta_bottle)) %>%
  dplyr::group_by(context) %>%
  dplyr::summarize(accuracy_bottle=mean(pred_bottle)) %>%
  dplyr::ungroup() 

overall_hums_c <- results %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pct_humans=mean(user_corr)) %>%
  dplyr::group_by(context) %>%
  dplyr::summarize(accuracy_human=mean(pct_humans)) %>%
  dplyr::ungroup() 

delta_bottle_v <- delta_bottle %>%
  dplyr::group_by(tripletid, context, speaker_OTH, speaker_TGT,
                  speaker_X, vowel_eng, vowel_fr) %>%
  dplyr::summarize(pred_bottle=mean(delta_bottle_s)) %>%
  dplyr::group_by(vowel_fr, vowel_eng) %>%
  dplyr::summarize(accuracy_bottle=mean(pred_bottle)) %>%
  dplyr::ungroup() 

bottle_humans_c <- dplyr::left_join(delta_bottle_c, overall_hums_c)

bottle_humans_v <- dplyr::left_join(delta_bottle_v, overall_hums_v)

```



```{r plot-nle-global-bottle-v}
ggplot2::ggplot(bottle_humans_v,
                ggplot2::aes(x=accuracy_bottle,
                             y=accuracy_human,
                             label=paste0(vowel_eng, ":", vowel_fr))) +
  ggplot2::geom_smooth(method="lm",  fullrange=TRUE, se=TRUE, lty="dashed",
                       lwd=0.6,  colour="#aaaaaa") +
  ggplot2::geom_point() +
  ggrepel::geom_text_repel(family="Times New Roman", size=4.9) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=17.5, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::labs(x=paste0("Bottleneck features predictions"),
                 y="Overall human accuracy") +
  #ggplot2::scale_x_continuous(expand=c(0,0), limits=c(0, 1.065)) +
  #ggplot2::coord_cartesian(xlim=c(0, 1.065), ylim=c(0, 1.01)) +
  ggplot2::ggsave("figures/Figure_Bottle_Humans.png", width=6, height=4)

```

```{r plot-nle-global-bottle-c}
ggplot2::ggplot(bottle_humans_c,
                ggplot2::aes(x=accuracy_bottle,
                             y=accuracy_human,
                             label=context)) +
  ggplot2::geom_smooth(method="lm",  fullrange=TRUE, se=TRUE, lty="dashed",
                       lwd=0.6,  colour="#aaaaaa") +
  ggplot2::geom_point() +
  ggrepel::geom_text_repel(family="Times New Roman", size=4.9) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=17.5, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::labs(x=paste0("Bottleneck features predictions"),
                 y="Overall human accuracy") #+
  #ggplot2::scale_x_continuous(expand=c(0,0), limits=c(-0.065, 0.065)) +
  #ggplot2::coord_cartesian(xlim=c(-0.065, 0.065), ylim=c(-0.45, 0.35)) +
  #ggplot2::ggsave("figures/Figure_Bottle_Humans.png", width=4, height=4)

```


```{r} 

delta_bottle_v_plot <- delta_bottle_v %>%
        dplyr::mutate(language = "Bottleneck Features")
ggplot2::ggplot(delta_bottle_v_plot,
                ggplot2::aes(x=`vowel_fr`, y=`vowel_eng`,
                fill=accuracy_bottle)) +
  ggplot2::geom_tile(colour="black") +
  ggplot2::scale_fill_gradient2(low = "black",
                                mid = "deepskyblue4",
                                high = "bisque",
                                midpoint=0.45,
                               limits = c(0, 1.00),
                               breaks=seq(0, 1.00, .1),
                               labels=as.character(seq(0, 1.00, .1)*100)) +
  emd_theme() +
  ggplot2::theme(legend.position = "bottom",
                 text=ggplot2::element_text(size=18, family="Times New Roman"),
                 axis.text=ggplot2::element_text(size=15, family="Times New Roman"),
                 legend.text=ggplot2::element_text(size=10, family="Times New Roman"),
                 legend.key.width=ggplot2::unit(1.75, "cm")) +
  ggplot2::guides(fill=ggplot2::guide_colourbar(title.position="bottom",
                                                title.hjust=0.5)) +
  ggplot2::labs(x="French vowel", y="English vowel", fill="Percent accuracy") +
  ggplot2::facet_grid(`language` ~ .) +
  ggplot2::ggsave("./Figures/Figure_Bottle.png", width=5, height=4)
```